repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]
        files: ^src/
      - id: ruff-format
        args: ["--config=pyproject.toml"]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        language: system
        args: ["--config-file=pyproject.toml"]
        files: ^src/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^tests/
      - id: trailing-whitespace
        exclude: ^tests/
      - id: debug-statements
        exclude: ^tests/
